### ISSUE TITLE
Bcbio RNASEq yaml file

### ISSUE THREAD

**Issue by kokyriakidis** [umccr/RNAseq-Analysis-Report#1]
Hello! Could you provide a reference yaml configuration file for the bcbio rnaseq pipeline? So as to be sure that I produce the right input for RNA-Seq report pipeline!

Thanks!

**Comment by skanwal** [comment]
Hello @kokyriakidis ,

The config file that we are currently using for our RNA samples is:
```
details:
  - analysis: RNA-seq
    genome_build: GRCh37
#    genome_build: hg38
    algorithm:
      aligner: star
      quality_format: standard
      trim_reads: false
      expression_caller: [kallisto]
      fusion_caller: [pizzly, arriba]
      tools_off: [gemini]
upload:
  dir: ../final
```

The two bcbio produced inputs that are required by the RNA-seq report pipeline are kallisto counts and fusions.
Hope this helps and let us know if you run into any issues.

----
Sehrish K.
